.PHONY: build test test-short lint infra-up infra-down
build: ; go build ./...
# Full suite. -p 1 serializes packages so the testcontainer-based suites
# (queue, store, integration) don't contend for Docker and flake under load.
test: ; go test -p 1 ./...
# Fast hermetic unit run: no Docker, no live models.
test-short: ; SKIP_DOCKER_TESTS=1 go test -short ./...
lint: ; go vet ./...
infra-up: ; docker compose -f deploy/compose/docker-compose.yml up -d
infra-down: ; docker compose -f deploy/compose/docker-compose.yml down
