.PHONY: build test lint infra-up infra-down
build: ; go build ./...
test: ; go test ./...
lint: ; go vet ./...
infra-up: ; docker compose -f deploy/compose/docker-compose.yml up -d
infra-down: ; docker compose -f deploy/compose/docker-compose.yml down
