// Package store provides storage adapters for NovaGrade. This file contains
// the Postgres database store backed by pgx/v5 connection pool and goose
// migrations.
//
// # Design notes
//
// The query layer is generated by sqlc (v1.31.1) from SQL files in
// internal/store/queries/. Generated code lives in internal/store/db and is
// committed to the repository so that `go build ./...` works without the sqlc
// binary present at build time.
//
// Migrations are embedded with //go:embed so they travel with the binary.
package store

import (
	"context"
	"embed"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"

	"github.com/azrtydxb/novagrade/internal/store/db"
	"github.com/azrtydxb/novagrade/pkg/contracts"
)

// ErrNotFound is returned by Store methods when the requested record does not exist.
var ErrNotFound = errors.New("store: not found")

// ErrDuplicate is returned by Store methods when a unique constraint is violated.
var ErrDuplicate = errors.New("store: duplicate")

// migrationFS holds the embedded SQL migration files.
//
//go:embed migrations/*.sql
var migrationFS embed.FS

// DBConfig holds connection settings for the Postgres database.
// No secrets are hardcoded; the caller always supplies them.
type DBConfig struct {
	Host     string // Postgres host name or IP
	Port     int    // Postgres port (default 5432)
	User     string // database user
	Password string // database password
	Database string // database name
	SSLMode  string // "disable", "require", "verify-full", …
}

// DSN formats a libpq-style connection string from the config.
func (c DBConfig) DSN() string {
	ssl := c.SSLMode
	if ssl == "" {
		ssl = "disable"
	}
	port := c.Port
	if port == 0 {
		port = 5432
	}
	return fmt.Sprintf(
		"host=%s port=%d user=%s password=%s dbname=%s sslmode=%s",
		c.Host, port, c.User, c.Password, c.Database, ssl,
	)
}

// Store wraps a pgxpool.Pool and exposes typed repository methods for the
// NovaGrade data model. It is safe for concurrent use.
type Store struct {
	pool    *pgxpool.Pool
	queries *db.Queries
}

// NewStore opens a pgxpool connection to Postgres using cfg and returns a
// *Store. It pings the database to verify connectivity before returning.
// Callers are responsible for calling Close when the store is no longer needed.
func NewStore(ctx context.Context, cfg DBConfig) (*Store, error) {
	pool, err := pgxpool.New(ctx, cfg.DSN())
	if err != nil {
		return nil, fmt.Errorf("store: open pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("store: ping: %w", err)
	}
	return &Store{pool: pool, queries: db.New(pool)}, nil
}

// Close releases all connections in the underlying pool.
func (s *Store) Close() {
	s.pool.Close()
}

// MigrateUp runs all pending goose migrations against the database that Store
// is connected to. Migration SQL files are embedded in the binary.
// It uses pgx's stdlib adapter to obtain a *sql.DB that goose can drive.
func (s *Store) MigrateUp(ctx context.Context) error {
	// Open a stdlib *sql.DB backed by the same pool config.
	sqlDB := stdlib.OpenDBFromPool(s.pool)
	defer func() { _ = sqlDB.Close() }()

	goose.SetBaseFS(migrationFS)
	if err := goose.SetDialect("postgres"); err != nil {
		return fmt.Errorf("store: goose set dialect: %w", err)
	}
	if err := goose.Up(sqlDB, "migrations"); err != nil {
		return fmt.Errorf("store: goose up: %w", err)
	}
	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Domain types
// ─────────────────────────────────────────────────────────────────────────────

// Submission is the Go representation of the submission row.
type Submission struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssessmentVersionID *uuid.UUID // nullable
	StudentID           *uuid.UUID // nullable
	State               contracts.SubmissionState
	CurrentStage        *string
	Attempt             int
	ErrorDetail         *string
	SourcePDFKey        *string
	TranscriptKey       *string
	GradedKey           *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// AuditEvent is the Go representation of the audit_event row.
type AuditEvent struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	EntityType string
	EntityID   *uuid.UUID // nullable
	Actor      string
	Action     string
	OldValue   []byte // raw JSON, nil when absent
	NewValue   []byte // raw JSON, nil when absent
	Reason     string
	CreatedAt  time.Time
}

// ─────────────────────────────────────────────────────────────────────────────
// CreateSubmission params
// ─────────────────────────────────────────────────────────────────────────────

// CreateSubmissionParams carries the values needed to insert a new submission.
type CreateSubmissionParams struct {
	TenantID            uuid.UUID
	AssessmentVersionID *uuid.UUID // optional
	StudentID           *uuid.UUID // optional
	SourcePDFKey        *string    // optional
}

// CreateSubmission inserts a new submission in the "uploaded" state and returns
// the full persisted row.
func (s *Store) CreateSubmission(ctx context.Context, p CreateSubmissionParams) (Submission, error) {
	row, err := s.queries.CreateSubmission(ctx, db.CreateSubmissionParams{
		TenantID:            p.TenantID,
		AssessmentVersionID: ptrUUIDToNullUUID(p.AssessmentVersionID),
		StudentID:           ptrUUIDToNullUUID(p.StudentID),
		State:               string(contracts.StateUploaded),
		SourcePdfKey:        ptrStringToPgtypeText(p.SourcePDFKey),
	})
	if err != nil {
		return Submission{}, fmt.Errorf("store: CreateSubmission: %w", err)
	}
	return submissionFromDB(row), nil
}

// SetSubmissionState updates the state column (and bumps updated_at) for the
// submission with the given id.
func (s *Store) SetSubmissionState(ctx context.Context, id uuid.UUID, state contracts.SubmissionState) error {
	n, err := s.queries.SetSubmissionState(ctx, db.SetSubmissionStateParams{
		State: string(state),
		ID:    id,
	})
	if err != nil {
		return fmt.Errorf("store: SetSubmissionState: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("store: SetSubmissionState %s: %w", id, ErrNotFound)
	}
	return nil
}

// FailSubmission marks the submission as failed, recording which stage failed
// in current_stage and a human-readable reason in error_detail (and bumps
// updated_at). It returns ErrNotFound when no row matched the given id.
func (s *Store) FailSubmission(ctx context.Context, id uuid.UUID, stage, detail string) error {
	n, err := s.queries.FailSubmission(ctx, db.FailSubmissionParams{
		ID:           id,
		CurrentStage: ptrStringToPgtypeText(&stage),
		ErrorDetail:  ptrStringToPgtypeText(&detail),
	})
	if err != nil {
		return fmt.Errorf("store: FailSubmission: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("store: FailSubmission %s: %w", id, ErrNotFound)
	}
	return nil
}

// ListSubmissionsByState returns submissions for a tenant, optionally filtered by state.
// Pass an empty string to return all submissions for the tenant.
func (s *Store) ListSubmissionsByState(ctx context.Context, tenantID uuid.UUID, state contracts.SubmissionState) ([]Submission, error) {
	rows, err := s.queries.ListSubmissionsByState(ctx, db.ListSubmissionsByStateParams{
		TenantID: tenantID,
		Column2:  string(state),
	})
	if err != nil {
		return nil, fmt.Errorf("store: ListSubmissionsByState: %w", err)
	}
	result := make([]Submission, 0, len(rows))
	for _, row := range rows {
		result = append(result, submissionFromDB(row))
	}
	return result, nil
}

// SetSourcePDFKey sets the source_pdf_key column (and bumps updated_at) for the
// submission with the given id. It returns ErrNotFound when no row matched.
func (s *Store) SetSourcePDFKey(ctx context.Context, id uuid.UUID, key string) error {
	n, err := s.queries.SetSourcePDFKey(ctx, db.SetSourcePDFKeyParams{
		ID:           id,
		SourcePdfKey: ptrStringToPgtypeText(&key),
	})
	if err != nil {
		return fmt.Errorf("store: SetSourcePDFKey: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("store: SetSourcePDFKey %s: %w", id, ErrNotFound)
	}
	return nil
}

// GetSubmission retrieves a single submission by primary key.
//
// TODO(phase2): SQL-level tenant filter. This lookup is by primary key only;
// every current caller checks the tenant handler-side (and the orchestrator
// validates env.TenantID against sub.TenantID). A defense-in-depth
// GetSubmissionForTenant that filters by tenant_id in the WHERE clause should be
// added so a tenant can never read another tenant's row even if a handler check
// is forgotten.
func (s *Store) GetSubmission(ctx context.Context, id uuid.UUID) (Submission, error) {
	row, err := s.queries.GetSubmission(ctx, id)
	if err != nil {
		if err == pgx.ErrNoRows {
			return Submission{}, fmt.Errorf("GetSubmission %s: %w", id, ErrNotFound)
		}
		return Submission{}, fmt.Errorf("store: GetSubmission: %w", err)
	}
	return submissionFromDB(row), nil
}

// ─────────────────────────────────────────────────────────────────────────────
// InsertAuditEvent
// ─────────────────────────────────────────────────────────────────────────────

// InsertAuditEventParams carries the values for a new audit_event row.
type InsertAuditEventParams struct {
	TenantID   uuid.UUID
	EntityType string
	EntityID   *uuid.UUID // optional
	Actor      string
	Action     string
	OldValue   []byte // raw JSON or nil
	NewValue   []byte // raw JSON or nil
	Reason     string
}

// InsertAuditEvent appends a new row to the append-only audit_event table.
// There are no update or delete methods for audit_event.
func (s *Store) InsertAuditEvent(ctx context.Context, p InsertAuditEventParams) (AuditEvent, error) {
	row, err := s.queries.InsertAuditEvent(ctx, db.InsertAuditEventParams{
		TenantID:   p.TenantID,
		EntityType: p.EntityType,
		EntityID:   ptrUUIDToNullUUID(p.EntityID),
		Actor:      p.Actor,
		Action:     p.Action,
		OldValue:   nullJSON(p.OldValue),
		NewValue:   nullJSON(p.NewValue),
		Reason:     p.Reason,
	})
	if err != nil {
		return AuditEvent{}, fmt.Errorf("store: InsertAuditEvent: %w", err)
	}
	return auditEventFromDB(row), nil
}

// ListAuditEventsBySubmission returns all audit_event rows for a given
// submission (entity_id) within the given tenant, ordered chronologically
// (oldest first). Only rows with entity_type = "submission" are returned.
// This is a read-only query — there is no update or delete path.
func (s *Store) ListAuditEventsBySubmission(ctx context.Context, tenantID, submissionID uuid.UUID) ([]AuditEvent, error) {
	rows, err := s.queries.ListAuditEventsBySubmission(ctx, db.ListAuditEventsBySubmissionParams{
		TenantID: tenantID,
		EntityID: ptrUUIDToNullUUID(&submissionID),
	})
	if err != nil {
		return nil, fmt.Errorf("store: ListAuditEventsBySubmission: %w", err)
	}
	result := make([]AuditEvent, 0, len(rows))
	for _, row := range rows {
		result = append(result, auditEventFromDB(row))
	}
	return result, nil
}

// ─────────────────────────────────────────────────────────────────────────────
// TeacherReview domain type and repository methods
// ─────────────────────────────────────────────────────────────────────────────

// TeacherReview is the public domain representation of a teacher_review row.
type TeacherReview struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	QuestionNo   string
	OldMarks     float64
	NewMarks     float64
	Feedback     string
	Comment      string
	Actor        string
	CreatedAt    time.Time
}

// InsertTeacherReviewParams carries the values for a new teacher_review row.
type InsertTeacherReviewParams struct {
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	QuestionNo   string
	OldMarks     float64
	NewMarks     float64
	Feedback     string
	Comment      string
	Actor        string
}

// InsertTeacherReview appends a per-question review row. It is append-only;
// callers may insert multiple rows for the same question_no to represent
// successive overrides.
func (s *Store) InsertTeacherReview(ctx context.Context, p InsertTeacherReviewParams) (TeacherReview, error) {
	row, err := s.queries.InsertTeacherReview(ctx, db.InsertTeacherReviewParams{
		TenantID:     p.TenantID,
		SubmissionID: p.SubmissionID,
		QuestionNo:   p.QuestionNo,
		OldMarks:     p.OldMarks,
		NewMarks:     p.NewMarks,
		Feedback:     p.Feedback,
		Comment:      p.Comment,
		Actor:        p.Actor,
	})
	if err != nil {
		return TeacherReview{}, fmt.Errorf("store: InsertTeacherReview: %w", err)
	}
	return teacherReviewFromDB(row), nil
}

// ListTeacherReviews returns all teacher_review rows for a submission within a
// tenant, ordered by created_at ASC (oldest first). The latest row per
// question_no represents the current override when merging.
func (s *Store) ListTeacherReviews(ctx context.Context, tenantID uuid.UUID, submissionID uuid.UUID) ([]TeacherReview, error) {
	rows, err := s.queries.ListTeacherReviews(ctx, db.ListTeacherReviewsParams{
		TenantID:     tenantID,
		SubmissionID: submissionID,
	})
	if err != nil {
		return nil, fmt.Errorf("store: ListTeacherReviews: %w", err)
	}
	result := make([]TeacherReview, 0, len(rows))
	for _, row := range rows {
		result = append(result, teacherReviewRowFromDB(row))
	}
	return result, nil
}

// ─────────────────────────────────────────────────────────────────────────────
// FinalGrade domain type and repository methods
// ─────────────────────────────────────────────────────────────────────────────

// FinalGrade is the public domain representation of a final_grade row.
// InsertFinalGrade uses UPSERT semantics: first approve inserts, re-approve after
// a regrade updates the row in place (updated_at bumps). Prior grades are preserved
// in the audit_event trail. There is no delete method.
type FinalGrade struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	Total        float64
	MaxTotal     float64
	Score100     float64
	GradedKey    string
	ApprovedBy   string
	ApprovedAt   time.Time
	CreatedAt    time.Time
}

// InsertFinalGradeParams carries the values for a new final_grade row.
type InsertFinalGradeParams struct {
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	Total        float64
	MaxTotal     float64
	Score100     float64
	GradedKey    string
	ApprovedBy   string
	ApprovedAt   time.Time
}

// InsertFinalGrade upserts an approval snapshot into final_grade and returns the
// persisted row. On first approve it inserts; on re-approve after a regrade it
// updates total/max_total/score_100/graded_key/approved_by/approved_at in place
// (updated_at bumps). Prior grades are preserved in the audit_event trail.
func (s *Store) InsertFinalGrade(ctx context.Context, p InsertFinalGradeParams) (FinalGrade, error) {
	row, err := s.queries.InsertFinalGrade(ctx, db.InsertFinalGradeParams{
		TenantID:     p.TenantID,
		SubmissionID: p.SubmissionID,
		Total:        p.Total,
		MaxTotal:     p.MaxTotal,
		Score100:     p.Score100,
		GradedKey:    p.GradedKey,
		ApprovedBy:   p.ApprovedBy,
		ApprovedAt:   pgtype.Timestamptz{Time: p.ApprovedAt, Valid: true},
	})
	if err != nil {
		return FinalGrade{}, fmt.Errorf("store: InsertFinalGrade: %w", err)
	}
	return finalGradeFromInsertRow(row), nil
}

// GetFinalGrade retrieves the final_grade row for the submission (at most one
// exists per tenant+submission); returns ErrNotFound if the submission has not
// been approved.
func (s *Store) GetFinalGrade(ctx context.Context, tenantID uuid.UUID, submissionID uuid.UUID) (FinalGrade, error) {
	row, err := s.queries.GetFinalGrade(ctx, db.GetFinalGradeParams{
		TenantID:     tenantID,
		SubmissionID: submissionID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return FinalGrade{}, fmt.Errorf("GetFinalGrade %s: %w", submissionID, ErrNotFound)
		}
		return FinalGrade{}, fmt.Errorf("store: GetFinalGrade: %w", err)
	}
	return finalGradeFromGetRow(row), nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Mapping helpers — db package types → public domain types
// ─────────────────────────────────────────────────────────────────────────────

// submissionFromDB converts a sqlc-generated db.Submission into the public
// Submission type, mapping pgtype nullable wrappers to Go pointer semantics.
func submissionFromDB(r db.Submission) Submission {
	return Submission{
		ID:                  r.ID,
		TenantID:            r.TenantID,
		AssessmentVersionID: nullUUIDToPtr(r.AssessmentVersionID),
		StudentID:           nullUUIDToPtr(r.StudentID),
		State:               contracts.SubmissionState(r.State),
		CurrentStage:        pgtypeTextToPtr(r.CurrentStage),
		Attempt:             int(r.Attempt),
		ErrorDetail:         pgtypeTextToPtr(r.ErrorDetail),
		SourcePDFKey:        pgtypeTextToPtr(r.SourcePdfKey),
		TranscriptKey:       pgtypeTextToPtr(r.TranscriptKey),
		GradedKey:           pgtypeTextToPtr(r.GradedKey),
		CreatedAt:           r.CreatedAt.Time,
		UpdatedAt:           r.UpdatedAt.Time,
	}
}

// auditEventFromDB converts a sqlc-generated db.AuditEvent into the public
// AuditEvent type.
func auditEventFromDB(r db.AuditEvent) AuditEvent {
	return AuditEvent{
		ID:         r.ID,
		TenantID:   r.TenantID,
		EntityType: r.EntityType,
		EntityID:   nullUUIDToPtr(r.EntityID),
		Actor:      r.Actor,
		Action:     r.Action,
		OldValue:   r.OldValue,
		NewValue:   r.NewValue,
		Reason:     r.Reason,
		CreatedAt:  r.CreatedAt.Time,
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Type conversion utilities
// ─────────────────────────────────────────────────────────────────────────────

func ptrUUIDToNullUUID(p *uuid.UUID) uuid.NullUUID {
	if p == nil {
		return uuid.NullUUID{}
	}
	return uuid.NullUUID{UUID: *p, Valid: true}
}

func nullUUIDToPtr(n uuid.NullUUID) *uuid.UUID {
	if !n.Valid {
		return nil
	}
	v := n.UUID
	return &v
}

func ptrStringToPgtypeText(p *string) pgtype.Text {
	if p == nil {
		return pgtype.Text{}
	}
	return pgtype.Text{String: *p, Valid: true}
}

func pgtypeTextToPtr(t pgtype.Text) *string {
	if !t.Valid {
		return nil
	}
	v := t.String
	return &v
}

// nullJSON returns nil when b is empty so pgx sends a SQL NULL instead of an
// empty byte slice (which would fail the jsonb cast).
func nullJSON(b []byte) []byte {
	if len(b) == 0 {
		return nil
	}
	return b
}

// teacherReviewFromDB converts a db.InsertTeacherReviewRow to the public TeacherReview type.
func teacherReviewFromDB(r db.InsertTeacherReviewRow) TeacherReview {
	return TeacherReview{
		ID:           r.ID,
		TenantID:     r.TenantID,
		SubmissionID: r.SubmissionID,
		QuestionNo:   r.QuestionNo,
		OldMarks:     r.OldMarks,
		NewMarks:     r.NewMarks,
		Feedback:     r.Feedback,
		Comment:      r.Comment,
		Actor:        r.Actor,
		CreatedAt:    r.CreatedAt.Time,
	}
}

// teacherReviewRowFromDB converts a db.ListTeacherReviewsRow to the public TeacherReview type.
func teacherReviewRowFromDB(r db.ListTeacherReviewsRow) TeacherReview {
	return TeacherReview{
		ID:           r.ID,
		TenantID:     r.TenantID,
		SubmissionID: r.SubmissionID,
		QuestionNo:   r.QuestionNo,
		OldMarks:     r.OldMarks,
		NewMarks:     r.NewMarks,
		Feedback:     r.Feedback,
		Comment:      r.Comment,
		Actor:        r.Actor,
		CreatedAt:    r.CreatedAt.Time,
	}
}

// finalGradeFromInsertRow converts a db.InsertFinalGradeRow to the public FinalGrade type.
func finalGradeFromInsertRow(r db.InsertFinalGradeRow) FinalGrade {
	return FinalGrade{
		ID:           r.ID,
		TenantID:     r.TenantID,
		SubmissionID: r.SubmissionID,
		Total:        r.Total,
		MaxTotal:     r.MaxTotal,
		Score100:     r.Score100,
		GradedKey:    r.GradedKey,
		ApprovedBy:   r.ApprovedBy,
		ApprovedAt:   r.ApprovedAt.Time,
		CreatedAt:    r.CreatedAt.Time,
	}
}

// finalGradeFromGetRow converts a db.GetFinalGradeRow to the public FinalGrade type.
func finalGradeFromGetRow(r db.GetFinalGradeRow) FinalGrade {
	return FinalGrade{
		ID:           r.ID,
		TenantID:     r.TenantID,
		SubmissionID: r.SubmissionID,
		Total:        r.Total,
		MaxTotal:     r.MaxTotal,
		Score100:     r.Score100,
		GradedKey:    r.GradedKey,
		ApprovedBy:   r.ApprovedBy,
		ApprovedAt:   r.ApprovedAt.Time,
		CreatedAt:    r.CreatedAt.Time,
	}
}

// Student is the public domain representation of a student row.
type Student struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	FullName  string
	CreatedAt time.Time
}

// UpsertStudent inserts or updates a student by (tenant_id, email).
func (s *Store) UpsertStudent(ctx context.Context, tenantID uuid.UUID, email, fullName string) (Student, error) {
	row, err := s.queries.UpsertStudent(ctx, db.UpsertStudentParams{
		TenantID: tenantID,
		Email:    email,
		FullName: fullName,
	})
	if err != nil {
		return Student{}, fmt.Errorf("store: UpsertStudent: %w", err)
	}
	return studentFromDB(row), nil
}

// GetStudent retrieves a student by tenant + id.
func (s *Store) GetStudent(ctx context.Context, tenantID, id uuid.UUID) (Student, error) {
	row, err := s.queries.GetStudent(ctx, db.GetStudentParams{TenantID: tenantID, ID: id})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return Student{}, fmt.Errorf("GetStudent %s: %w", id, ErrNotFound)
		}
		return Student{}, fmt.Errorf("store: GetStudent: %w", err)
	}
	return studentFromDB(row), nil
}

// ListSubmissionsByAssessmentVersion returns all submissions for a tenant + avid.
func (s *Store) ListSubmissionsByAssessmentVersion(ctx context.Context, tenantID, avid uuid.UUID) ([]Submission, error) {
	rows, err := s.queries.ListSubmissionsByAssessmentVersion(ctx, db.ListSubmissionsByAssessmentVersionParams{
		TenantID:            tenantID,
		AssessmentVersionID: uuid.NullUUID{UUID: avid, Valid: true},
	})
	if err != nil {
		return nil, fmt.Errorf("store: ListSubmissionsByAssessmentVersion: %w", err)
	}
	result := make([]Submission, 0, len(rows))
	for _, row := range rows {
		result = append(result, submissionFromDB(row))
	}
	return result, nil
}

// GetAssessmentVersionTenantID returns the tenant_id that owns the assessment
// version with the given id. Returns ErrNotFound if no such row exists.
func (s *Store) GetAssessmentVersionTenantID(ctx context.Context, avid uuid.UUID) (uuid.UUID, error) {
	tenantID, err := s.queries.GetAssessmentVersionTenantID(ctx, avid)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return uuid.UUID{}, fmt.Errorf("GetAssessmentVersionTenantID %s: %w", avid, ErrNotFound)
		}
		return uuid.UUID{}, fmt.Errorf("store: GetAssessmentVersionTenantID: %w", err)
	}
	return tenantID, nil
}

func studentFromDB(r db.Student) Student {
	return Student{
		ID:        r.ID,
		TenantID:  r.TenantID,
		Email:     r.Email,
		FullName:  r.FullName,
		CreatedAt: r.CreatedAt.Time,
	}
}
