// Package store provides storage adapters for NovaGrade. This file contains
// the Postgres database store backed by pgx/v5 connection pool and goose
// migrations.
//
// # Design notes
//
// The query layer is generated by sqlc (v1.31.1) from SQL files in
// internal/store/queries/. Generated code lives in internal/store/db and is
// committed to the repository so that `go build ./...` works without the sqlc
// binary present at build time.
//
// Migrations are embedded with //go:embed so they travel with the binary.
package store

import (
	"context"
	"embed"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"

	"github.com/azrtydxb/novagrade/internal/store/db"
	"github.com/azrtydxb/novagrade/pkg/contracts"
)

// ErrNotFound is returned by Store methods when the requested record does not exist.
var ErrNotFound = errors.New("store: not found")

// migrationFS holds the embedded SQL migration files.
//
//go:embed migrations/*.sql
var migrationFS embed.FS

// DBConfig holds connection settings for the Postgres database.
// No secrets are hardcoded; the caller always supplies them.
type DBConfig struct {
	Host     string // Postgres host name or IP
	Port     int    // Postgres port (default 5432)
	User     string // database user
	Password string // database password
	Database string // database name
	SSLMode  string // "disable", "require", "verify-full", …
}

// DSN formats a libpq-style connection string from the config.
func (c DBConfig) DSN() string {
	ssl := c.SSLMode
	if ssl == "" {
		ssl = "disable"
	}
	port := c.Port
	if port == 0 {
		port = 5432
	}
	return fmt.Sprintf(
		"host=%s port=%d user=%s password=%s dbname=%s sslmode=%s",
		c.Host, port, c.User, c.Password, c.Database, ssl,
	)
}

// Store wraps a pgxpool.Pool and exposes typed repository methods for the
// NovaGrade data model. It is safe for concurrent use.
type Store struct {
	pool    *pgxpool.Pool
	queries *db.Queries
}

// NewStore opens a pgxpool connection to Postgres using cfg and returns a
// *Store. It pings the database to verify connectivity before returning.
// Callers are responsible for calling Close when the store is no longer needed.
func NewStore(ctx context.Context, cfg DBConfig) (*Store, error) {
	pool, err := pgxpool.New(ctx, cfg.DSN())
	if err != nil {
		return nil, fmt.Errorf("store: open pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("store: ping: %w", err)
	}
	return &Store{pool: pool, queries: db.New(pool)}, nil
}

// Close releases all connections in the underlying pool.
func (s *Store) Close() {
	s.pool.Close()
}

// MigrateUp runs all pending goose migrations against the database that Store
// is connected to. Migration SQL files are embedded in the binary.
// It uses pgx's stdlib adapter to obtain a *sql.DB that goose can drive.
func (s *Store) MigrateUp(ctx context.Context) error {
	// Open a stdlib *sql.DB backed by the same pool config.
	sqlDB := stdlib.OpenDBFromPool(s.pool)
	defer func() { _ = sqlDB.Close() }()

	goose.SetBaseFS(migrationFS)
	if err := goose.SetDialect("postgres"); err != nil {
		return fmt.Errorf("store: goose set dialect: %w", err)
	}
	if err := goose.Up(sqlDB, "migrations"); err != nil {
		return fmt.Errorf("store: goose up: %w", err)
	}
	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Domain types
// ─────────────────────────────────────────────────────────────────────────────

// Submission is the Go representation of the submission row.
type Submission struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssessmentVersionID *uuid.UUID // nullable
	StudentID           *uuid.UUID // nullable
	State               contracts.SubmissionState
	CurrentStage        *string
	Attempt             int
	ErrorDetail         *string
	SourcePDFKey        *string
	TranscriptKey       *string
	GradedKey           *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// AuditEvent is the Go representation of the audit_event row.
type AuditEvent struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	EntityType string
	EntityID   *uuid.UUID // nullable
	Actor      string
	Action     string
	OldValue   []byte // raw JSON, nil when absent
	NewValue   []byte // raw JSON, nil when absent
	Reason     string
	CreatedAt  time.Time
}

// ─────────────────────────────────────────────────────────────────────────────
// CreateSubmission params
// ─────────────────────────────────────────────────────────────────────────────

// CreateSubmissionParams carries the values needed to insert a new submission.
type CreateSubmissionParams struct {
	TenantID            uuid.UUID
	AssessmentVersionID *uuid.UUID // optional
	StudentID           *uuid.UUID // optional
	SourcePDFKey        *string    // optional
}

// CreateSubmission inserts a new submission in the "uploaded" state and returns
// the full persisted row.
func (s *Store) CreateSubmission(ctx context.Context, p CreateSubmissionParams) (Submission, error) {
	row, err := s.queries.CreateSubmission(ctx, db.CreateSubmissionParams{
		TenantID:            p.TenantID,
		AssessmentVersionID: ptrUUIDToNullUUID(p.AssessmentVersionID),
		StudentID:           ptrUUIDToNullUUID(p.StudentID),
		State:               string(contracts.StateUploaded),
		SourcePdfKey:        ptrStringToPgtypeText(p.SourcePDFKey),
	})
	if err != nil {
		return Submission{}, fmt.Errorf("store: CreateSubmission: %w", err)
	}
	return submissionFromDB(row), nil
}

// SetSubmissionState updates the state column (and bumps updated_at) for the
// submission with the given id.
func (s *Store) SetSubmissionState(ctx context.Context, id uuid.UUID, state contracts.SubmissionState) error {
	n, err := s.queries.SetSubmissionState(ctx, db.SetSubmissionStateParams{
		State: string(state),
		ID:    id,
	})
	if err != nil {
		return fmt.Errorf("store: SetSubmissionState: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("store: SetSubmissionState %s: %w", id, ErrNotFound)
	}
	return nil
}

// FailSubmission marks the submission as failed, recording which stage failed
// in current_stage and a human-readable reason in error_detail (and bumps
// updated_at). It returns ErrNotFound when no row matched the given id.
func (s *Store) FailSubmission(ctx context.Context, id uuid.UUID, stage, detail string) error {
	n, err := s.queries.FailSubmission(ctx, db.FailSubmissionParams{
		ID:           id,
		CurrentStage: ptrStringToPgtypeText(&stage),
		ErrorDetail:  ptrStringToPgtypeText(&detail),
	})
	if err != nil {
		return fmt.Errorf("store: FailSubmission: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("store: FailSubmission %s: %w", id, ErrNotFound)
	}
	return nil
}

// ListSubmissionsByState returns submissions for a tenant, optionally filtered by state.
// Pass an empty string to return all submissions for the tenant.
func (s *Store) ListSubmissionsByState(ctx context.Context, tenantID uuid.UUID, state contracts.SubmissionState) ([]Submission, error) {
	rows, err := s.queries.ListSubmissionsByState(ctx, db.ListSubmissionsByStateParams{
		TenantID: tenantID,
		Column2:  string(state),
	})
	if err != nil {
		return nil, fmt.Errorf("store: ListSubmissionsByState: %w", err)
	}
	result := make([]Submission, 0, len(rows))
	for _, row := range rows {
		result = append(result, submissionFromDB(row))
	}
	return result, nil
}

// SetSourcePDFKey sets the source_pdf_key column (and bumps updated_at) for the
// submission with the given id. It returns ErrNotFound when no row matched.
func (s *Store) SetSourcePDFKey(ctx context.Context, id uuid.UUID, key string) error {
	n, err := s.queries.SetSourcePDFKey(ctx, db.SetSourcePDFKeyParams{
		ID:           id,
		SourcePdfKey: ptrStringToPgtypeText(&key),
	})
	if err != nil {
		return fmt.Errorf("store: SetSourcePDFKey: %w", err)
	}
	if n == 0 {
		return fmt.Errorf("store: SetSourcePDFKey %s: %w", id, ErrNotFound)
	}
	return nil
}

// GetSubmission retrieves a single submission by primary key.
func (s *Store) GetSubmission(ctx context.Context, id uuid.UUID) (Submission, error) {
	row, err := s.queries.GetSubmission(ctx, id)
	if err != nil {
		if err == pgx.ErrNoRows {
			return Submission{}, fmt.Errorf("GetSubmission %s: %w", id, ErrNotFound)
		}
		return Submission{}, fmt.Errorf("store: GetSubmission: %w", err)
	}
	return submissionFromDB(row), nil
}

// ─────────────────────────────────────────────────────────────────────────────
// InsertAuditEvent
// ─────────────────────────────────────────────────────────────────────────────

// InsertAuditEventParams carries the values for a new audit_event row.
type InsertAuditEventParams struct {
	TenantID   uuid.UUID
	EntityType string
	EntityID   *uuid.UUID // optional
	Actor      string
	Action     string
	OldValue   []byte // raw JSON or nil
	NewValue   []byte // raw JSON or nil
	Reason     string
}

// InsertAuditEvent appends a new row to the append-only audit_event table.
// There are no update or delete methods for audit_event.
func (s *Store) InsertAuditEvent(ctx context.Context, p InsertAuditEventParams) (AuditEvent, error) {
	row, err := s.queries.InsertAuditEvent(ctx, db.InsertAuditEventParams{
		TenantID:   p.TenantID,
		EntityType: p.EntityType,
		EntityID:   ptrUUIDToNullUUID(p.EntityID),
		Actor:      p.Actor,
		Action:     p.Action,
		OldValue:   nullJSON(p.OldValue),
		NewValue:   nullJSON(p.NewValue),
		Reason:     p.Reason,
	})
	if err != nil {
		return AuditEvent{}, fmt.Errorf("store: InsertAuditEvent: %w", err)
	}
	return auditEventFromDB(row), nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Mapping helpers — db package types → public domain types
// ─────────────────────────────────────────────────────────────────────────────

// submissionFromDB converts a sqlc-generated db.Submission into the public
// Submission type, mapping pgtype nullable wrappers to Go pointer semantics.
func submissionFromDB(r db.Submission) Submission {
	return Submission{
		ID:                  r.ID,
		TenantID:            r.TenantID,
		AssessmentVersionID: nullUUIDToPtr(r.AssessmentVersionID),
		StudentID:           nullUUIDToPtr(r.StudentID),
		State:               contracts.SubmissionState(r.State),
		CurrentStage:        pgtypeTextToPtr(r.CurrentStage),
		Attempt:             int(r.Attempt),
		ErrorDetail:         pgtypeTextToPtr(r.ErrorDetail),
		SourcePDFKey:        pgtypeTextToPtr(r.SourcePdfKey),
		TranscriptKey:       pgtypeTextToPtr(r.TranscriptKey),
		GradedKey:           pgtypeTextToPtr(r.GradedKey),
		CreatedAt:           r.CreatedAt.Time,
		UpdatedAt:           r.UpdatedAt.Time,
	}
}

// auditEventFromDB converts a sqlc-generated db.AuditEvent into the public
// AuditEvent type.
func auditEventFromDB(r db.AuditEvent) AuditEvent {
	return AuditEvent{
		ID:         r.ID,
		TenantID:   r.TenantID,
		EntityType: r.EntityType,
		EntityID:   nullUUIDToPtr(r.EntityID),
		Actor:      r.Actor,
		Action:     r.Action,
		OldValue:   r.OldValue,
		NewValue:   r.NewValue,
		Reason:     r.Reason,
		CreatedAt:  r.CreatedAt.Time,
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// Type conversion utilities
// ─────────────────────────────────────────────────────────────────────────────

func ptrUUIDToNullUUID(p *uuid.UUID) uuid.NullUUID {
	if p == nil {
		return uuid.NullUUID{}
	}
	return uuid.NullUUID{UUID: *p, Valid: true}
}

func nullUUIDToPtr(n uuid.NullUUID) *uuid.UUID {
	if !n.Valid {
		return nil
	}
	v := n.UUID
	return &v
}

func ptrStringToPgtypeText(p *string) pgtype.Text {
	if p == nil {
		return pgtype.Text{}
	}
	return pgtype.Text{String: *p, Valid: true}
}

func pgtypeTextToPtr(t pgtype.Text) *string {
	if !t.Valid {
		return nil
	}
	v := t.String
	return &v
}

// nullJSON returns nil when b is empty so pgx sends a SQL NULL instead of an
// empty byte slice (which would fail the jsonb cast).
func nullJSON(b []byte) []byte {
	if len(b) == 0 {
		return nil
	}
	return b
}
