// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_provider.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearTenantDefaultAIProvider = `-- name: ClearTenantDefaultAIProvider :exec
UPDATE ai_provider_config
SET is_default = false
WHERE tenant_id = $1 AND is_default = true
`

func (q *Queries) ClearTenantDefaultAIProvider(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearTenantDefaultAIProvider, tenantID)
	return err
}

const getDefaultAIProviderConfigWithKey = `-- name: GetDefaultAIProviderConfigWithKey :one
SELECT id, tenant_id, name, provider_type, base_url, model, api_key_enc, is_default, created_at
FROM ai_provider_config
WHERE tenant_id = $1 AND is_default = true
`

func (q *Queries) GetDefaultAIProviderConfigWithKey(ctx context.Context, tenantID uuid.UUID) (AiProviderConfig, error) {
	row := q.db.QueryRow(ctx, getDefaultAIProviderConfigWithKey, tenantID)
	var i AiProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ProviderType,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKeyEnc,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const insertAIProviderConfig = `-- name: InsertAIProviderConfig :one
INSERT INTO ai_provider_config (tenant_id, name, provider_type, base_url, model, api_key_enc)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, provider_type, base_url, model, api_key_enc, is_default, created_at
`

type InsertAIProviderConfigParams struct {
	TenantID     uuid.UUID
	Name         string
	ProviderType string
	BaseUrl      string
	Model        string
	ApiKeyEnc    []byte
}

func (q *Queries) InsertAIProviderConfig(ctx context.Context, arg InsertAIProviderConfigParams) (AiProviderConfig, error) {
	row := q.db.QueryRow(ctx, insertAIProviderConfig,
		arg.TenantID,
		arg.Name,
		arg.ProviderType,
		arg.BaseUrl,
		arg.Model,
		arg.ApiKeyEnc,
	)
	var i AiProviderConfig
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ProviderType,
		&i.BaseUrl,
		&i.Model,
		&i.ApiKeyEnc,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const listAIProviderConfigs = `-- name: ListAIProviderConfigs :many
SELECT id, tenant_id, name, provider_type, base_url, model, is_default, created_at
FROM ai_provider_config
WHERE tenant_id = $1
ORDER BY name
`

type ListAIProviderConfigsRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	ProviderType string
	BaseUrl      string
	Model        string
	IsDefault    bool
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListAIProviderConfigs(ctx context.Context, tenantID uuid.UUID) ([]ListAIProviderConfigsRow, error) {
	rows, err := q.db.Query(ctx, listAIProviderConfigs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIProviderConfigsRow
	for rows.Next() {
		var i ListAIProviderConfigsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ProviderType,
			&i.BaseUrl,
			&i.Model,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAIProviderDefault = `-- name: SetAIProviderDefault :execrows
UPDATE ai_provider_config
SET is_default = true
WHERE id = $1 AND tenant_id = $2
`

type SetAIProviderDefaultParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) SetAIProviderDefault(ctx context.Context, arg SetAIProviderDefaultParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAIProviderDefault, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
