// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appeal.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAppeal = `-- name: GetAppeal :one
SELECT id, tenant_id, submission_id, status, reason, requested_by, resolution, created_at, updated_at
FROM appeal
WHERE id = $1 AND tenant_id = $2
`

type GetAppealParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetAppeal(ctx context.Context, arg GetAppealParams) (Appeal, error) {
	row := q.db.QueryRow(ctx, getAppeal, arg.ID, arg.TenantID)
	var i Appeal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubmissionID,
		&i.Status,
		&i.Reason,
		&i.RequestedBy,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAppeal = `-- name: InsertAppeal :one
INSERT INTO appeal (tenant_id, submission_id, reason, requested_by)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, submission_id, status, reason, requested_by, resolution, created_at, updated_at
`

type InsertAppealParams struct {
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	Reason       string
	RequestedBy  string
}

func (q *Queries) InsertAppeal(ctx context.Context, arg InsertAppealParams) (Appeal, error) {
	row := q.db.QueryRow(ctx, insertAppeal,
		arg.TenantID,
		arg.SubmissionID,
		arg.Reason,
		arg.RequestedBy,
	)
	var i Appeal
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubmissionID,
		&i.Status,
		&i.Reason,
		&i.RequestedBy,
		&i.Resolution,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppeals = `-- name: ListAppeals :many
SELECT id, tenant_id, submission_id, status, reason, requested_by, resolution, created_at, updated_at
FROM appeal
WHERE tenant_id = $1
  AND ($2 = '' OR status = $2)
ORDER BY created_at DESC
`

type ListAppealsParams struct {
	TenantID uuid.UUID
	Column2  interface{}
}

func (q *Queries) ListAppeals(ctx context.Context, arg ListAppealsParams) ([]Appeal, error) {
	rows, err := q.db.Query(ctx, listAppeals, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appeal
	for rows.Next() {
		var i Appeal
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubmissionID,
			&i.Status,
			&i.Reason,
			&i.RequestedBy,
			&i.Resolution,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppealStatus = `-- name: UpdateAppealStatus :execrows
UPDATE appeal
SET status = $3, resolution = $4, updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateAppealStatusParams struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	Status     string
	Resolution string
}

func (q *Queries) UpdateAppealStatus(ctx context.Context, arg UpdateAppealStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAppealStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.Resolution,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
