// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assessment_version.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getAssessmentVersionTenantID = `-- name: GetAssessmentVersionTenantID :one
SELECT tenant_id FROM assessment_version WHERE id = $1
`

func (q *Queries) GetAssessmentVersionTenantID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAssessmentVersionTenantID, id)
	var tenant_id uuid.UUID
	err := row.Scan(&tenant_id)
	return tenant_id, err
}
