// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_event.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_event (
    tenant_id, entity_type, entity_id,
    actor, action, old_value, new_value, reason
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING
    id, tenant_id, entity_type, entity_id,
    actor, action, old_value, new_value, reason,
    created_at
`

type InsertAuditEventParams struct {
	TenantID   uuid.UUID
	EntityType string
	EntityID   uuid.NullUUID
	Actor      string
	Action     string
	OldValue   []byte
	NewValue   []byte
	Reason     string
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.TenantID,
		arg.EntityType,
		arg.EntityID,
		arg.Actor,
		arg.Action,
		arg.OldValue,
		arg.NewValue,
		arg.Reason,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityType,
		&i.EntityID,
		&i.Actor,
		&i.Action,
		&i.OldValue,
		&i.NewValue,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}
