// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_event.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_event (
    tenant_id, entity_type, entity_id,
    actor, action, old_value, new_value, reason
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING
    id, tenant_id, entity_type, entity_id,
    actor, action, old_value, new_value, reason,
    created_at
`

type InsertAuditEventParams struct {
	TenantID   uuid.UUID
	EntityType string
	EntityID   uuid.NullUUID
	Actor      string
	Action     string
	OldValue   []byte
	NewValue   []byte
	Reason     string
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.TenantID,
		arg.EntityType,
		arg.EntityID,
		arg.Actor,
		arg.Action,
		arg.OldValue,
		arg.NewValue,
		arg.Reason,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityType,
		&i.EntityID,
		&i.Actor,
		&i.Action,
		&i.OldValue,
		&i.NewValue,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEventsBySubmission = `-- name: ListAuditEventsBySubmission :many
SELECT
    id, tenant_id, entity_type, entity_id,
    actor, action, old_value, new_value, reason,
    created_at
FROM audit_event
WHERE tenant_id = $1
  AND entity_type = 'submission'
  AND entity_id = $2
ORDER BY created_at ASC
`

type ListAuditEventsBySubmissionParams struct {
	TenantID uuid.UUID
	EntityID uuid.NullUUID
}

// Returns all audit_event rows for a specific submission (entity_id) scoped
// to the given tenant, ordered chronologically (oldest first).
// Only rows with entity_type = 'submission' are returned.
func (q *Queries) ListAuditEventsBySubmission(ctx context.Context, arg ListAuditEventsBySubmissionParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsBySubmission, arg.TenantID, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityType,
			&i.EntityID,
			&i.Actor,
			&i.Action,
			&i.OldValue,
			&i.NewValue,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
