// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: curriculum.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCurriculumOutcome = `-- name: GetCurriculumOutcome :one
SELECT id, tenant_id, code, description, subject, created_at
FROM curriculum_outcome
WHERE id = $1 AND tenant_id = $2
`

type GetCurriculumOutcomeParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetCurriculumOutcome(ctx context.Context, arg GetCurriculumOutcomeParams) (CurriculumOutcome, error) {
	row := q.db.QueryRow(ctx, getCurriculumOutcome, arg.ID, arg.TenantID)
	var i CurriculumOutcome
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Description,
		&i.Subject,
		&i.CreatedAt,
	)
	return i, err
}

const insertCurriculumOutcome = `-- name: InsertCurriculumOutcome :one
INSERT INTO curriculum_outcome (tenant_id, code, description, subject)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, code, description, subject, created_at
`

type InsertCurriculumOutcomeParams struct {
	TenantID    uuid.UUID
	Code        string
	Description string
	Subject     string
}

func (q *Queries) InsertCurriculumOutcome(ctx context.Context, arg InsertCurriculumOutcomeParams) (CurriculumOutcome, error) {
	row := q.db.QueryRow(ctx, insertCurriculumOutcome,
		arg.TenantID,
		arg.Code,
		arg.Description,
		arg.Subject,
	)
	var i CurriculumOutcome
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Description,
		&i.Subject,
		&i.CreatedAt,
	)
	return i, err
}

const insertQuestionOutcome = `-- name: InsertQuestionOutcome :one
INSERT INTO question_outcome (tenant_id, assessment_version_id, question_no, outcome_id)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, assessment_version_id, question_no, outcome_id, created_at
`

type InsertQuestionOutcomeParams struct {
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
	QuestionNo          string
	OutcomeID           uuid.UUID
}

func (q *Queries) InsertQuestionOutcome(ctx context.Context, arg InsertQuestionOutcomeParams) (QuestionOutcome, error) {
	row := q.db.QueryRow(ctx, insertQuestionOutcome,
		arg.TenantID,
		arg.AssessmentVersionID,
		arg.QuestionNo,
		arg.OutcomeID,
	)
	var i QuestionOutcome
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentVersionID,
		&i.QuestionNo,
		&i.OutcomeID,
		&i.CreatedAt,
	)
	return i, err
}

const listCurriculumOutcomes = `-- name: ListCurriculumOutcomes :many
SELECT id, tenant_id, code, description, subject, created_at
FROM curriculum_outcome
WHERE tenant_id = $1
ORDER BY code
`

func (q *Queries) ListCurriculumOutcomes(ctx context.Context, tenantID uuid.UUID) ([]CurriculumOutcome, error) {
	rows, err := q.db.Query(ctx, listCurriculumOutcomes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CurriculumOutcome
	for rows.Next() {
		var i CurriculumOutcome
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Description,
			&i.Subject,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionOutcomes = `-- name: ListQuestionOutcomes :many
SELECT id, tenant_id, assessment_version_id, question_no, outcome_id, created_at
FROM question_outcome
WHERE tenant_id = $1 AND assessment_version_id = $2
ORDER BY question_no
`

type ListQuestionOutcomesParams struct {
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
}

func (q *Queries) ListQuestionOutcomes(ctx context.Context, arg ListQuestionOutcomesParams) ([]QuestionOutcome, error) {
	rows, err := q.db.Query(ctx, listQuestionOutcomes, arg.TenantID, arg.AssessmentVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionOutcome
	for rows.Next() {
		var i QuestionOutcome
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssessmentVersionID,
			&i.QuestionNo,
			&i.OutcomeID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
