// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: final_grade.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFinalGrade = `-- name: GetFinalGrade :one
SELECT
    id, tenant_id, submission_id,
    total, max_total, score_100,
    graded_key, approved_by, approved_at,
    created_at
FROM final_grade
WHERE tenant_id     = $1
  AND submission_id = $2
`

type GetFinalGradeParams struct {
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
}

type GetFinalGradeRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	Total        float64
	MaxTotal     float64
	Score100     float64
	GradedKey    string
	ApprovedBy   string
	ApprovedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) GetFinalGrade(ctx context.Context, arg GetFinalGradeParams) (GetFinalGradeRow, error) {
	row := q.db.QueryRow(ctx, getFinalGrade, arg.TenantID, arg.SubmissionID)
	var i GetFinalGradeRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubmissionID,
		&i.Total,
		&i.MaxTotal,
		&i.Score100,
		&i.GradedKey,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertFinalGrade = `-- name: InsertFinalGrade :one
INSERT INTO final_grade (
    tenant_id, submission_id,
    total, max_total, score_100,
    graded_key, approved_by, approved_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING
    id, tenant_id, submission_id,
    total, max_total, score_100,
    graded_key, approved_by, approved_at,
    created_at
`

type InsertFinalGradeParams struct {
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	Total        float64
	MaxTotal     float64
	Score100     float64
	GradedKey    string
	ApprovedBy   string
	ApprovedAt   pgtype.Timestamptz
}

type InsertFinalGradeRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	Total        float64
	MaxTotal     float64
	Score100     float64
	GradedKey    string
	ApprovedBy   string
	ApprovedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertFinalGrade(ctx context.Context, arg InsertFinalGradeParams) (InsertFinalGradeRow, error) {
	row := q.db.QueryRow(ctx, insertFinalGrade,
		arg.TenantID,
		arg.SubmissionID,
		arg.Total,
		arg.MaxTotal,
		arg.Score100,
		arg.GradedKey,
		arg.ApprovedBy,
		arg.ApprovedAt,
	)
	var i InsertFinalGradeRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubmissionID,
		&i.Total,
		&i.MaxTotal,
		&i.Score100,
		&i.GradedKey,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}
