// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteIntegrationConnection = `-- name: DeleteIntegrationConnection :execrows
DELETE FROM integration_connection
WHERE id = $1
  AND tenant_id = $2
`

type DeleteIntegrationConnectionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteIntegrationConnection(ctx context.Context, arg DeleteIntegrationConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIntegrationConnection, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIntegrationConnectionWithCreds = `-- name: GetIntegrationConnectionWithCreds :one
SELECT id, tenant_id, category, provider, config, credentials, status, created_at, updated_at
FROM integration_connection
WHERE id = $1
  AND tenant_id = $2
`

type GetIntegrationConnectionWithCredsParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetIntegrationConnectionWithCreds(ctx context.Context, arg GetIntegrationConnectionWithCredsParams) (IntegrationConnection, error) {
	row := q.db.QueryRow(ctx, getIntegrationConnectionWithCreds, arg.ID, arg.TenantID)
	var i IntegrationConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Category,
		&i.Provider,
		&i.Config,
		&i.Credentials,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationConnections = `-- name: ListIntegrationConnections :many
SELECT id, tenant_id, category, provider, config, status, created_at, updated_at
FROM integration_connection
WHERE tenant_id = $1
ORDER BY created_at
`

type ListIntegrationConnectionsRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Category  string
	Provider  string
	Config    []byte
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListIntegrationConnections(ctx context.Context, tenantID uuid.UUID) ([]ListIntegrationConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listIntegrationConnections, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIntegrationConnectionsRow
	for rows.Next() {
		var i ListIntegrationConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Category,
			&i.Provider,
			&i.Config,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertIntegrationConnection = `-- name: UpsertIntegrationConnection :one
INSERT INTO integration_connection (tenant_id, category, provider, config, credentials, status)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, category, provider)
DO UPDATE SET
    config      = EXCLUDED.config,
    credentials = EXCLUDED.credentials,
    status      = EXCLUDED.status,
    updated_at  = now()
RETURNING id, tenant_id, category, provider, config, credentials, status, created_at, updated_at
`

type UpsertIntegrationConnectionParams struct {
	TenantID    uuid.UUID
	Category    string
	Provider    string
	Config      []byte
	Credentials []byte
	Status      string
}

func (q *Queries) UpsertIntegrationConnection(ctx context.Context, arg UpsertIntegrationConnectionParams) (IntegrationConnection, error) {
	row := q.db.QueryRow(ctx, upsertIntegrationConnection,
		arg.TenantID,
		arg.Category,
		arg.Provider,
		arg.Config,
		arg.Credentials,
		arg.Status,
	)
	var i IntegrationConnection
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Category,
		&i.Provider,
		&i.Config,
		&i.Credentials,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
