// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: marking_guide.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestGuide = `-- name: GetLatestGuide :one
SELECT
    id, tenant_id, assessment_version_id, version, name,
    content, locked, locked_at, created_at
FROM marking_guide
WHERE tenant_id             = $1
  AND assessment_version_id = $2
ORDER BY version DESC
LIMIT 1
`

type GetLatestGuideParams struct {
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
}

type GetLatestGuideRow struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
	Version             int32
	Name                pgtype.Text
	Content             []byte
	Locked              bool
	LockedAt            pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

// Returns the highest-version marking_guide row for the given tenant + assessment_version.
func (q *Queries) GetLatestGuide(ctx context.Context, arg GetLatestGuideParams) (GetLatestGuideRow, error) {
	row := q.db.QueryRow(ctx, getLatestGuide, arg.TenantID, arg.AssessmentVersionID)
	var i GetLatestGuideRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentVersionID,
		&i.Version,
		&i.Name,
		&i.Content,
		&i.Locked,
		&i.LockedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertGuideVersion = `-- name: InsertGuideVersion :one
INSERT INTO marking_guide (
    tenant_id, assessment_version_id, name, content, version
)
SELECT
    $1,
    $2,
    $3,
    $4,
    COALESCE((
        SELECT MAX(version)
        FROM marking_guide
        WHERE tenant_id             = $1
          AND assessment_version_id = $2
    ), 0) + 1
RETURNING
    id, tenant_id, assessment_version_id, version, name,
    content, locked, locked_at, created_at
`

type InsertGuideVersionParams struct {
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
	Name                pgtype.Text
	Content             []byte
}

type InsertGuideVersionRow struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
	Version             int32
	Name                pgtype.Text
	Content             []byte
	Locked              bool
	LockedAt            pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

// Inserts a new marking_guide version. The version number is computed atomically
// as COALESCE(MAX(version), 0) + 1 within the (tenant_id, assessment_version_id)
// scope, so callers never supply it — it is always auto-incremented by the DB.
func (q *Queries) InsertGuideVersion(ctx context.Context, arg InsertGuideVersionParams) (InsertGuideVersionRow, error) {
	row := q.db.QueryRow(ctx, insertGuideVersion,
		arg.TenantID,
		arg.AssessmentVersionID,
		arg.Name,
		arg.Content,
	)
	var i InsertGuideVersionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentVersionID,
		&i.Version,
		&i.Name,
		&i.Content,
		&i.Locked,
		&i.LockedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listGuideVersions = `-- name: ListGuideVersions :many
SELECT
    id, tenant_id, assessment_version_id, version, name,
    content, locked, locked_at, created_at
FROM marking_guide
WHERE tenant_id             = $1
  AND assessment_version_id = $2
ORDER BY version DESC
`

type ListGuideVersionsParams struct {
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
}

type ListGuideVersionsRow struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
	Version             int32
	Name                pgtype.Text
	Content             []byte
	Locked              bool
	LockedAt            pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

// Returns all marking_guide versions for a tenant + assessment_version, newest first.
func (q *Queries) ListGuideVersions(ctx context.Context, arg ListGuideVersionsParams) ([]ListGuideVersionsRow, error) {
	rows, err := q.db.Query(ctx, listGuideVersions, arg.TenantID, arg.AssessmentVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuideVersionsRow
	for rows.Next() {
		var i ListGuideVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssessmentVersionID,
			&i.Version,
			&i.Name,
			&i.Content,
			&i.Locked,
			&i.LockedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGuide = `-- name: LockGuide :execrows
UPDATE marking_guide
   SET locked    = true,
       locked_at = now()
 WHERE tenant_id = $1
   AND id        = $2
`

type LockGuideParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// Sets locked=true and locked_at=now() for the given guide. Tenant-scoped.
func (q *Queries) LockGuide(ctx context.Context, arg LockGuideParams) (int64, error) {
	result, err := q.db.Exec(ctx, lockGuide, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
