// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicYear struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Label     string
	StartDate pgtype.Date
	EndDate   pgtype.Date
	CreatedAt pgtype.Timestamptz
}

type AiGradingResult struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	Content      []byte
	Model        string
	CreatedAt    pgtype.Timestamptz
}

type ApiKey struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	KeyHash     string
	Description string
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Appeal struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	Status       string
	Reason       string
	RequestedBy  string
	Resolution   string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Assessment struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	CourseID  uuid.NullUUID
	Title     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AssessmentVersion struct {
	ID            uuid.UUID
	TenantID      uuid.UUID
	AssessmentID  uuid.UUID
	VersionNumber int32
	PublishedAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type AuditEvent struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	EntityType string
	EntityID   uuid.NullUUID
	Actor      string
	Action     string
	OldValue   []byte
	NewValue   []byte
	Reason     string
	CreatedAt  pgtype.Timestamptz
}

type Class struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	CourseID  uuid.NullUUID
	Label     string
	CreatedAt pgtype.Timestamptz
}

type Course struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	DepartmentID uuid.NullUUID
	Code         string
	Name         string
	CreatedAt    pgtype.Timestamptz
}

type Department struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Feedback struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	Content      string
	CreatedAt    pgtype.Timestamptz
}

type FinalGrade struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	Marks        pgtype.Numeric
	Percentage   pgtype.Numeric
	GradeLetter  pgtype.Text
	CreatedAt    pgtype.Timestamptz
	Total        float64
	MaxTotal     float64
	Score100     float64
	GradedKey    string
	ApprovedBy   string
	ApprovedAt   pgtype.Timestamptz
}

type IntegrationConnection struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Category    string
	Provider    string
	Config      []byte
	Credentials []byte
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type MarkingGuide struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
	Content             []byte
	CreatedAt           pgtype.Timestamptz
	Version             int32
	Name                pgtype.Text
	Locked              bool
	LockedAt            pgtype.Timestamptz
}

type ModerationMark struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	SessionID      uuid.UUID
	SubmissionID   uuid.UUID
	QuestionNo     string
	ModeratorMarks float64
	Moderator      string
	CreatedAt      pgtype.Timestamptz
}

type ModerationSession struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
	CreatedBy           string
	SampleSize          int32
	Status              string
	CreatedAt           pgtype.Timestamptz
}

type ModerationSessionSubmission struct {
	SessionID    uuid.UUID
	SubmissionID uuid.UUID
	TenantID     uuid.UUID
}

type PageImage struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	PageNumber   int32
	StorageKey   string
	CreatedAt    pgtype.Timestamptz
}

type Principal struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	FullName  string
	CreatedAt pgtype.Timestamptz
}

type Question struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
	Sequence            int32
	Stem                string
	MaxMarks            pgtype.Numeric
	CreatedAt           pgtype.Timestamptz
}

type Role struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	Name        string
	Permissions []byte
	CreatedAt   pgtype.Timestamptz
}

type Rubric struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
	Content             []byte
	CreatedAt           pgtype.Timestamptz
}

type School struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	Country   string
	Timezone  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Student struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	FullName  string
	CreatedAt pgtype.Timestamptz
}

type Submission struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	AssessmentVersionID uuid.NullUUID
	StudentID           uuid.NullUUID
	State               string
	CurrentStage        pgtype.Text
	Attempt             int32
	ErrorDetail         pgtype.Text
	SourcePdfKey        pgtype.Text
	TranscriptKey       pgtype.Text
	GradedKey           pgtype.Text
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type Teacher struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Email     string
	FullName  string
	CreatedAt pgtype.Timestamptz
}

type TeacherReview struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	TeacherID    uuid.NullUUID
	Notes        string
	ReviewedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	QuestionNo   string
	OldMarks     float64
	NewMarks     float64
	Feedback     string
	Comment      string
	Actor        string
}

type Term struct {
	ID             uuid.UUID
	TenantID       uuid.UUID
	AcademicYearID uuid.UUID
	Label          string
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	CreatedAt      pgtype.Timestamptz
}

type Transcription struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	Content      []byte
	Model        string
	CreatedAt    pgtype.Timestamptz
}

type Tunable struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Key       string
	Value     []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type WebhookSubscription struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Event     string
	Url       string
	Secret    []byte
	Active    bool
	CreatedAt pgtype.Timestamptz
}
