// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getModerationSession = `-- name: GetModerationSession :one
SELECT id, tenant_id, assessment_version_id, created_by, sample_size, status, created_at
FROM moderation_session
WHERE id        = $1
  AND tenant_id = $2
`

type GetModerationSessionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetModerationSession(ctx context.Context, arg GetModerationSessionParams) (ModerationSession, error) {
	row := q.db.QueryRow(ctx, getModerationSession, arg.ID, arg.TenantID)
	var i ModerationSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentVersionID,
		&i.CreatedBy,
		&i.SampleSize,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertModerationMark = `-- name: InsertModerationMark :one
INSERT INTO moderation_mark (
    tenant_id, session_id, submission_id, question_no, moderator_marks, moderator
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, tenant_id, session_id, submission_id, question_no, moderator_marks, moderator, created_at
`

type InsertModerationMarkParams struct {
	TenantID       uuid.UUID
	SessionID      uuid.UUID
	SubmissionID   uuid.UUID
	QuestionNo     string
	ModeratorMarks float64
	Moderator      string
}

func (q *Queries) InsertModerationMark(ctx context.Context, arg InsertModerationMarkParams) (ModerationMark, error) {
	row := q.db.QueryRow(ctx, insertModerationMark,
		arg.TenantID,
		arg.SessionID,
		arg.SubmissionID,
		arg.QuestionNo,
		arg.ModeratorMarks,
		arg.Moderator,
	)
	var i ModerationMark
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SessionID,
		&i.SubmissionID,
		&i.QuestionNo,
		&i.ModeratorMarks,
		&i.Moderator,
		&i.CreatedAt,
	)
	return i, err
}

const insertModerationSession = `-- name: InsertModerationSession :one
INSERT INTO moderation_session (
    tenant_id, assessment_version_id, created_by, sample_size, status
) VALUES (
    $1, $2, $3, $4, 'open'
)
RETURNING id, tenant_id, assessment_version_id, created_by, sample_size, status, created_at
`

type InsertModerationSessionParams struct {
	TenantID            uuid.UUID
	AssessmentVersionID uuid.UUID
	CreatedBy           string
	SampleSize          int32
}

func (q *Queries) InsertModerationSession(ctx context.Context, arg InsertModerationSessionParams) (ModerationSession, error) {
	row := q.db.QueryRow(ctx, insertModerationSession,
		arg.TenantID,
		arg.AssessmentVersionID,
		arg.CreatedBy,
		arg.SampleSize,
	)
	var i ModerationSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentVersionID,
		&i.CreatedBy,
		&i.SampleSize,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertModerationSessionSubmission = `-- name: InsertModerationSessionSubmission :exec
INSERT INTO moderation_session_submission (session_id, submission_id, tenant_id)
VALUES ($1, $2, $3)
`

type InsertModerationSessionSubmissionParams struct {
	SessionID    uuid.UUID
	SubmissionID uuid.UUID
	TenantID     uuid.UUID
}

func (q *Queries) InsertModerationSessionSubmission(ctx context.Context, arg InsertModerationSessionSubmissionParams) error {
	_, err := q.db.Exec(ctx, insertModerationSessionSubmission, arg.SessionID, arg.SubmissionID, arg.TenantID)
	return err
}

const listModerationMarks = `-- name: ListModerationMarks :many
SELECT id, tenant_id, session_id, submission_id, question_no, moderator_marks, moderator, created_at
FROM moderation_mark
WHERE session_id = $1
  AND tenant_id  = $2
ORDER BY created_at
`

type ListModerationMarksParams struct {
	SessionID uuid.UUID
	TenantID  uuid.UUID
}

func (q *Queries) ListModerationMarks(ctx context.Context, arg ListModerationMarksParams) ([]ModerationMark, error) {
	rows, err := q.db.Query(ctx, listModerationMarks, arg.SessionID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationMark
	for rows.Next() {
		var i ModerationMark
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SessionID,
			&i.SubmissionID,
			&i.QuestionNo,
			&i.ModeratorMarks,
			&i.Moderator,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModerationSessionSubmissions = `-- name: ListModerationSessionSubmissions :many
SELECT submission_id
FROM moderation_session_submission
WHERE session_id = $1
  AND tenant_id  = $2
ORDER BY submission_id
`

type ListModerationSessionSubmissionsParams struct {
	SessionID uuid.UUID
	TenantID  uuid.UUID
}

func (q *Queries) ListModerationSessionSubmissions(ctx context.Context, arg ListModerationSessionSubmissionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listModerationSessionSubmissions, arg.SessionID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var submission_id uuid.UUID
		if err := rows.Scan(&submission_id); err != nil {
			return nil, err
		}
		items = append(items, submission_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sampleSubmissionsByAssessmentVersion = `-- name: SampleSubmissionsByAssessmentVersion :many
SELECT id
FROM submission
WHERE tenant_id              = $1
  AND assessment_version_id  = $2
ORDER BY id
LIMIT $3
`

type SampleSubmissionsByAssessmentVersionParams struct {
	TenantID            uuid.UUID
	AssessmentVersionID uuid.NullUUID
	Limit               int32
}

// Deterministic sampling: ORDER BY id LIMIT sample_size.
// Ordered by id (uuid primary key) for reproducibility — tests can pre-create
// submissions and predict which are sampled. NOT random, enabling deterministic tests.
func (q *Queries) SampleSubmissionsByAssessmentVersion(ctx context.Context, arg SampleSubmissionsByAssessmentVersionParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, sampleSubmissionsByAssessmentVersion, arg.TenantID, arg.AssessmentVersionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
