// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	DeleteIntegrationConnection(ctx context.Context, arg DeleteIntegrationConnectionParams) (int64, error)
	FailSubmission(ctx context.Context, arg FailSubmissionParams) (int64, error)
	GetFinalGrade(ctx context.Context, arg GetFinalGradeParams) (GetFinalGradeRow, error)
	GetIntegrationConnectionWithCreds(ctx context.Context, arg GetIntegrationConnectionWithCredsParams) (IntegrationConnection, error)
	// Returns the highest-version marking_guide row for the given tenant + assessment_version.
	GetLatestGuide(ctx context.Context, arg GetLatestGuideParams) (GetLatestGuideRow, error)
	GetStudent(ctx context.Context, arg GetStudentParams) (Student, error)
	GetSubmission(ctx context.Context, id uuid.UUID) (Submission, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	InsertFinalGrade(ctx context.Context, arg InsertFinalGradeParams) (InsertFinalGradeRow, error)
	// Inserts a new marking_guide version. The version number is computed atomically
	// as COALESCE(MAX(version), 0) + 1 within the (tenant_id, assessment_version_id)
	// scope, so callers never supply it — it is always auto-incremented by the DB.
	InsertGuideVersion(ctx context.Context, arg InsertGuideVersionParams) (InsertGuideVersionRow, error)
	InsertTeacherReview(ctx context.Context, arg InsertTeacherReviewParams) (InsertTeacherReviewRow, error)
	// Returns all audit_event rows for a specific submission (entity_id) scoped
	// to the given tenant, ordered chronologically (oldest first).
	// Only rows with entity_type = 'submission' are returned.
	ListAuditEventsBySubmission(ctx context.Context, arg ListAuditEventsBySubmissionParams) ([]AuditEvent, error)
	// Returns all marking_guide versions for a tenant + assessment_version, newest first.
	ListGuideVersions(ctx context.Context, arg ListGuideVersionsParams) ([]ListGuideVersionsRow, error)
	ListIntegrationConnections(ctx context.Context, tenantID uuid.UUID) ([]ListIntegrationConnectionsRow, error)
	ListSubmissionsByAssessmentVersion(ctx context.Context, arg ListSubmissionsByAssessmentVersionParams) ([]Submission, error)
	// When $2 is the empty string, no state filter is applied (all states match).
	ListSubmissionsByState(ctx context.Context, arg ListSubmissionsByStateParams) ([]Submission, error)
	ListTeacherReviews(ctx context.Context, arg ListTeacherReviewsParams) ([]ListTeacherReviewsRow, error)
	// Sets locked=true and locked_at=now() for the given guide. Tenant-scoped.
	LockGuide(ctx context.Context, arg LockGuideParams) (int64, error)
	SetSourcePDFKey(ctx context.Context, arg SetSourcePDFKeyParams) (int64, error)
	SetSubmissionState(ctx context.Context, arg SetSubmissionStateParams) (int64, error)
	UpsertIntegrationConnection(ctx context.Context, arg UpsertIntegrationConnectionParams) (IntegrationConnection, error)
	UpsertStudent(ctx context.Context, arg UpsertStudentParams) (Student, error)
}

var _ Querier = (*Queries)(nil)
