// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error)
	CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (WebhookSubscription, error)
	DeleteIntegrationConnection(ctx context.Context, arg DeleteIntegrationConnectionParams) (int64, error)
	DeleteWebhookSubscription(ctx context.Context, arg DeleteWebhookSubscriptionParams) (int64, error)
	FailSubmission(ctx context.Context, arg FailSubmissionParams) (int64, error)
	GetActiveWebhooksForEvent(ctx context.Context, arg GetActiveWebhooksForEventParams) ([]WebhookSubscription, error)
	GetAppeal(ctx context.Context, arg GetAppealParams) (Appeal, error)
	GetAssessmentVersionTenantID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetFinalGrade(ctx context.Context, arg GetFinalGradeParams) (GetFinalGradeRow, error)
	GetIntegrationConnectionWithCreds(ctx context.Context, arg GetIntegrationConnectionWithCredsParams) (IntegrationConnection, error)
	// Returns the highest-version marking_guide row for the given tenant + assessment_version.
	GetLatestGuide(ctx context.Context, arg GetLatestGuideParams) (GetLatestGuideRow, error)
	GetModerationSession(ctx context.Context, arg GetModerationSessionParams) (ModerationSession, error)
	GetStudent(ctx context.Context, arg GetStudentParams) (Student, error)
	GetSubmission(ctx context.Context, id uuid.UUID) (Submission, error)
	InsertAppeal(ctx context.Context, arg InsertAppealParams) (Appeal, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditEvent, error)
	InsertFinalGrade(ctx context.Context, arg InsertFinalGradeParams) (InsertFinalGradeRow, error)
	// Inserts a new marking_guide version. The version number is computed atomically
	// as COALESCE(MAX(version), 0) + 1 within the (tenant_id, assessment_version_id)
	// scope, so callers never supply it — it is always auto-incremented by the DB.
	InsertGuideVersion(ctx context.Context, arg InsertGuideVersionParams) (InsertGuideVersionRow, error)
	InsertModerationMark(ctx context.Context, arg InsertModerationMarkParams) (ModerationMark, error)
	InsertModerationSession(ctx context.Context, arg InsertModerationSessionParams) (ModerationSession, error)
	InsertModerationSessionSubmission(ctx context.Context, arg InsertModerationSessionSubmissionParams) error
	InsertTeacherReview(ctx context.Context, arg InsertTeacherReviewParams) (InsertTeacherReviewRow, error)
	ListAppeals(ctx context.Context, arg ListAppealsParams) ([]Appeal, error)
	// Returns all audit_event rows for a specific submission (entity_id) scoped
	// to the given tenant, ordered chronologically (oldest first).
	// Only rows with entity_type = 'submission' are returned.
	ListAuditEventsBySubmission(ctx context.Context, arg ListAuditEventsBySubmissionParams) ([]AuditEvent, error)
	// Returns all marking_guide versions for a tenant + assessment_version, newest first.
	ListGuideVersions(ctx context.Context, arg ListGuideVersionsParams) ([]ListGuideVersionsRow, error)
	ListIntegrationConnections(ctx context.Context, tenantID uuid.UUID) ([]ListIntegrationConnectionsRow, error)
	ListModerationMarks(ctx context.Context, arg ListModerationMarksParams) ([]ModerationMark, error)
	ListModerationSessionSubmissions(ctx context.Context, arg ListModerationSessionSubmissionsParams) ([]uuid.UUID, error)
	ListSubmissionsByAssessmentVersion(ctx context.Context, arg ListSubmissionsByAssessmentVersionParams) ([]Submission, error)
	// When $2 is the empty string, no state filter is applied (all states match).
	ListSubmissionsByState(ctx context.Context, arg ListSubmissionsByStateParams) ([]Submission, error)
	ListTeacherReviews(ctx context.Context, arg ListTeacherReviewsParams) ([]ListTeacherReviewsRow, error)
	ListWebhookSubscriptions(ctx context.Context, tenantID uuid.UUID) ([]ListWebhookSubscriptionsRow, error)
	// Sets locked=true and locked_at=now() for the given guide. Tenant-scoped.
	LockGuide(ctx context.Context, arg LockGuideParams) (int64, error)
	// Deterministic sampling: ORDER BY id LIMIT sample_size.
	// Ordered by id (uuid primary key) for reproducibility — tests can pre-create
	// submissions and predict which are sampled. NOT random, enabling deterministic tests.
	SampleSubmissionsByAssessmentVersion(ctx context.Context, arg SampleSubmissionsByAssessmentVersionParams) ([]uuid.UUID, error)
	SetSourcePDFKey(ctx context.Context, arg SetSourcePDFKeyParams) (int64, error)
	SetSubmissionState(ctx context.Context, arg SetSubmissionStateParams) (int64, error)
	UpdateAppealStatus(ctx context.Context, arg UpdateAppealStatusParams) (int64, error)
	UpsertIntegrationConnection(ctx context.Context, arg UpsertIntegrationConnectionParams) (IntegrationConnection, error)
	UpsertStudent(ctx context.Context, arg UpsertStudentParams) (Student, error)
}

var _ Querier = (*Queries)(nil)
