// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getStudent = `-- name: GetStudent :one
SELECT id, tenant_id, email, full_name, created_at
FROM student
WHERE tenant_id = $1 AND id = $2
`

type GetStudentParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetStudent(ctx context.Context, arg GetStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, arg.TenantID, arg.ID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}

const upsertStudent = `-- name: UpsertStudent :one
INSERT INTO student (id, tenant_id, email, full_name)
VALUES (gen_random_uuid(), $1, $2, $3)
ON CONFLICT (tenant_id, email)
DO UPDATE SET full_name = EXCLUDED.full_name
RETURNING id, tenant_id, email, full_name, created_at
`

type UpsertStudentParams struct {
	TenantID uuid.UUID
	Email    string
	FullName string
}

func (q *Queries) UpsertStudent(ctx context.Context, arg UpsertStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, upsertStudent, arg.TenantID, arg.Email, arg.FullName)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.FullName,
		&i.CreatedAt,
	)
	return i, err
}
