// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submission.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submission (
    tenant_id, assessment_version_id, student_id,
    state, attempt, source_pdf_key
) VALUES (
    $1, $2, $3,
    $4, 0, $5
)
RETURNING
    id, tenant_id, assessment_version_id, student_id,
    state, current_stage, attempt, error_detail,
    source_pdf_key, transcript_key, graded_key,
    created_at, updated_at
`

type CreateSubmissionParams struct {
	TenantID            uuid.UUID
	AssessmentVersionID uuid.NullUUID
	StudentID           uuid.NullUUID
	State               string
	SourcePdfKey        pgtype.Text
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.TenantID,
		arg.AssessmentVersionID,
		arg.StudentID,
		arg.State,
		arg.SourcePdfKey,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentVersionID,
		&i.StudentID,
		&i.State,
		&i.CurrentStage,
		&i.Attempt,
		&i.ErrorDetail,
		&i.SourcePdfKey,
		&i.TranscriptKey,
		&i.GradedKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failSubmission = `-- name: FailSubmission :execrows
UPDATE submission
   SET state         = 'failed',
       current_stage = $2,
       error_detail  = $3,
       updated_at    = now()
 WHERE id = $1
`

type FailSubmissionParams struct {
	ID           uuid.UUID
	CurrentStage pgtype.Text
	ErrorDetail  pgtype.Text
}

func (q *Queries) FailSubmission(ctx context.Context, arg FailSubmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, failSubmission, arg.ID, arg.CurrentStage, arg.ErrorDetail)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubmission = `-- name: GetSubmission :one
SELECT
    id, tenant_id, assessment_version_id, student_id,
    state, current_stage, attempt, error_detail,
    source_pdf_key, transcript_key, graded_key,
    created_at, updated_at
FROM submission
WHERE id = $1
`

func (q *Queries) GetSubmission(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmission, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentVersionID,
		&i.StudentID,
		&i.State,
		&i.CurrentStage,
		&i.Attempt,
		&i.ErrorDetail,
		&i.SourcePdfKey,
		&i.TranscriptKey,
		&i.GradedKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSubmissionState = `-- name: SetSubmissionState :execrows
UPDATE submission
   SET state      = $1,
       updated_at = now()
 WHERE id = $2
`

type SetSubmissionStateParams struct {
	State string
	ID    uuid.UUID
}

func (q *Queries) SetSubmissionState(ctx context.Context, arg SetSubmissionStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSubmissionState, arg.State, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
