// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: submission.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submission (
    tenant_id, assessment_version_id, student_id,
    state, attempt, source_pdf_key
) VALUES (
    $1, $2, $3,
    $4, 0, $5
)
RETURNING
    id, tenant_id, assessment_version_id, student_id,
    state, current_stage, attempt, error_detail,
    source_pdf_key, transcript_key, graded_key,
    created_at, updated_at
`

type CreateSubmissionParams struct {
	TenantID            uuid.UUID
	AssessmentVersionID uuid.NullUUID
	StudentID           uuid.NullUUID
	State               string
	SourcePdfKey        pgtype.Text
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.TenantID,
		arg.AssessmentVersionID,
		arg.StudentID,
		arg.State,
		arg.SourcePdfKey,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentVersionID,
		&i.StudentID,
		&i.State,
		&i.CurrentStage,
		&i.Attempt,
		&i.ErrorDetail,
		&i.SourcePdfKey,
		&i.TranscriptKey,
		&i.GradedKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failSubmission = `-- name: FailSubmission :execrows
UPDATE submission
   SET state         = 'failed',
       current_stage = $2,
       error_detail  = $3,
       updated_at    = now()
 WHERE id = $1
`

type FailSubmissionParams struct {
	ID           uuid.UUID
	CurrentStage pgtype.Text
	ErrorDetail  pgtype.Text
}

func (q *Queries) FailSubmission(ctx context.Context, arg FailSubmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, failSubmission, arg.ID, arg.CurrentStage, arg.ErrorDetail)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubmission = `-- name: GetSubmission :one
SELECT
    id, tenant_id, assessment_version_id, student_id,
    state, current_stage, attempt, error_detail,
    source_pdf_key, transcript_key, graded_key,
    created_at, updated_at
FROM submission
WHERE id = $1
`

func (q *Queries) GetSubmission(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmission, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssessmentVersionID,
		&i.StudentID,
		&i.State,
		&i.CurrentStage,
		&i.Attempt,
		&i.ErrorDetail,
		&i.SourcePdfKey,
		&i.TranscriptKey,
		&i.GradedKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubmissionsByState = `-- name: ListSubmissionsByState :many
SELECT
    id, tenant_id, assessment_version_id, student_id,
    state, current_stage, attempt, error_detail,
    source_pdf_key, transcript_key, graded_key,
    created_at, updated_at
FROM submission
WHERE tenant_id = $1
  AND ($2 = '' OR state = $2)
ORDER BY created_at DESC
`

type ListSubmissionsByStateParams struct {
	TenantID uuid.UUID
	Column2  interface{}
}

// When $2 is the empty string, no state filter is applied (all states match).
func (q *Queries) ListSubmissionsByState(ctx context.Context, arg ListSubmissionsByStateParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByState, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssessmentVersionID,
			&i.StudentID,
			&i.State,
			&i.CurrentStage,
			&i.Attempt,
			&i.ErrorDetail,
			&i.SourcePdfKey,
			&i.TranscriptKey,
			&i.GradedKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSourcePDFKey = `-- name: SetSourcePDFKey :execrows
UPDATE submission
   SET source_pdf_key = $2,
       updated_at     = now()
 WHERE id = $1
`

type SetSourcePDFKeyParams struct {
	ID           uuid.UUID
	SourcePdfKey pgtype.Text
}

func (q *Queries) SetSourcePDFKey(ctx context.Context, arg SetSourcePDFKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSourcePDFKey, arg.ID, arg.SourcePdfKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSubmissionState = `-- name: SetSubmissionState :execrows
UPDATE submission
   SET state      = $1,
       updated_at = now()
 WHERE id = $2
`

type SetSubmissionStateParams struct {
	State string
	ID    uuid.UUID
}

func (q *Queries) SetSubmissionState(ctx context.Context, arg SetSubmissionStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSubmissionState, arg.State, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSubmissionsByAssessmentVersion = `-- name: ListSubmissionsByAssessmentVersion :many
SELECT id, tenant_id, assessment_version_id, student_id,
    state, current_stage, attempt, error_detail,
    source_pdf_key, transcript_key, graded_key,
    created_at, updated_at
FROM submission
WHERE tenant_id = $1
  AND assessment_version_id = $2
ORDER BY created_at DESC
`

type ListSubmissionsByAssessmentVersionParams struct {
	TenantID            uuid.UUID
	AssessmentVersionID uuid.NullUUID
}

func (q *Queries) ListSubmissionsByAssessmentVersion(ctx context.Context, arg ListSubmissionsByAssessmentVersionParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByAssessmentVersion, arg.TenantID, arg.AssessmentVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssessmentVersionID,
			&i.StudentID,
			&i.State,
			&i.CurrentStage,
			&i.Attempt,
			&i.ErrorDetail,
			&i.SourcePdfKey,
			&i.TranscriptKey,
			&i.GradedKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
