// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teacher_review.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertTeacherReview = `-- name: InsertTeacherReview :one
INSERT INTO teacher_review (
    tenant_id, submission_id,
    question_no, old_marks, new_marks,
    feedback, comment, actor
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING
    id, tenant_id, submission_id,
    question_no, old_marks, new_marks,
    feedback, comment, actor,
    created_at
`

type InsertTeacherReviewParams struct {
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	QuestionNo   string
	OldMarks     float64
	NewMarks     float64
	Feedback     string
	Comment      string
	Actor        string
}

type InsertTeacherReviewRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	QuestionNo   string
	OldMarks     float64
	NewMarks     float64
	Feedback     string
	Comment      string
	Actor        string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertTeacherReview(ctx context.Context, arg InsertTeacherReviewParams) (InsertTeacherReviewRow, error) {
	row := q.db.QueryRow(ctx, insertTeacherReview,
		arg.TenantID,
		arg.SubmissionID,
		arg.QuestionNo,
		arg.OldMarks,
		arg.NewMarks,
		arg.Feedback,
		arg.Comment,
		arg.Actor,
	)
	var i InsertTeacherReviewRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubmissionID,
		&i.QuestionNo,
		&i.OldMarks,
		&i.NewMarks,
		&i.Feedback,
		&i.Comment,
		&i.Actor,
		&i.CreatedAt,
	)
	return i, err
}

const listTeacherReviews = `-- name: ListTeacherReviews :many
SELECT
    id, tenant_id, submission_id,
    question_no, old_marks, new_marks,
    feedback, comment, actor,
    created_at
FROM teacher_review
WHERE tenant_id     = $1
  AND submission_id = $2
ORDER BY created_at ASC, id ASC
`

type ListTeacherReviewsParams struct {
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
}

type ListTeacherReviewsRow struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	SubmissionID uuid.UUID
	QuestionNo   string
	OldMarks     float64
	NewMarks     float64
	Feedback     string
	Comment      string
	Actor        string
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) ListTeacherReviews(ctx context.Context, arg ListTeacherReviewsParams) ([]ListTeacherReviewsRow, error) {
	rows, err := q.db.Query(ctx, listTeacherReviews, arg.TenantID, arg.SubmissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeacherReviewsRow
	for rows.Next() {
		var i ListTeacherReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubmissionID,
			&i.QuestionNo,
			&i.OldMarks,
			&i.NewMarks,
			&i.Feedback,
			&i.Comment,
			&i.Actor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
