// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookSubscription = `-- name: CreateWebhookSubscription :one
INSERT INTO webhook_subscription (tenant_id, event, url, secret)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, event, url, secret, active, created_at
`

type CreateWebhookSubscriptionParams struct {
	TenantID uuid.UUID
	Event    string
	Url      string
	Secret   []byte
}

func (q *Queries) CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (WebhookSubscription, error) {
	row := q.db.QueryRow(ctx, createWebhookSubscription,
		arg.TenantID,
		arg.Event,
		arg.Url,
		arg.Secret,
	)
	var i WebhookSubscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Event,
		&i.Url,
		&i.Secret,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhookSubscription = `-- name: DeleteWebhookSubscription :execrows
DELETE FROM webhook_subscription
WHERE id = $1
  AND tenant_id = $2
`

type DeleteWebhookSubscriptionParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) DeleteWebhookSubscription(ctx context.Context, arg DeleteWebhookSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookSubscription, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveWebhooksForEvent = `-- name: GetActiveWebhooksForEvent :many
SELECT id, tenant_id, event, url, secret, active, created_at
FROM webhook_subscription
WHERE tenant_id = $1
  AND event = $2
  AND active = true
`

type GetActiveWebhooksForEventParams struct {
	TenantID uuid.UUID
	Event    string
}

func (q *Queries) GetActiveWebhooksForEvent(ctx context.Context, arg GetActiveWebhooksForEventParams) ([]WebhookSubscription, error) {
	rows, err := q.db.Query(ctx, getActiveWebhooksForEvent, arg.TenantID, arg.Event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookSubscription
	for rows.Next() {
		var i WebhookSubscription
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Event,
			&i.Url,
			&i.Secret,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookSubscriptions = `-- name: ListWebhookSubscriptions :many
SELECT id, tenant_id, event, url, active, created_at
FROM webhook_subscription
WHERE tenant_id = $1
ORDER BY created_at
`

type ListWebhookSubscriptionsRow struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Event     string
	Url       string
	Active    bool
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListWebhookSubscriptions(ctx context.Context, tenantID uuid.UUID) ([]ListWebhookSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listWebhookSubscriptions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWebhookSubscriptionsRow
	for rows.Next() {
		var i ListWebhookSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Event,
			&i.Url,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
